name: Docker image build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  docker-image-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Build the Docker image
      run: |
        docker build \
        -t "tdpdne:dev" \
        -f "src/TDPDNE.Telegram.Bot/Dockerfile" \
        ${{github.workspace}}/src